id: 458f713849764bb3b59681802c8bacc4
initial_creation_type: ocr
source_metadata:
  volumes:
    7d5470b051834fbb866acd3400e6a8b6:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
