id: D7E965304
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:43:22+00:00'
last_modified: '2022-05-26T07:59:33.979704+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    db5f:
      image_group_id: I1PD95856
      title: སྤྱོད་པའི་གླུའི་འགྲེལ་པ།
      total_pages: 2107
      order: 11
      base_file: db5f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
